name: Deploy to VPS

on:
  push:
    branches:
      - main #

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add VPS to known hosts
      run: ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

    - name: Copy project to VPS
      run: |
        ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "mkdir -p /opt/lovely-list"
        rsync -avz --exclude 'node_modules' --exclude '.git' --exclude 'database.db' ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/opt/lovely-list/

    - name: Build and deploy Docker container on VPS
      run: |
        ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
          cd /opt/lovely-list && \
          docker compose down || true && \
          docker compose build --no-cache && \
          docker compose up -d
        "