name: Deploy to VPS

on:
  # Déclencheur automatique quand tu push sur la branche main
  push:
    branches: [ "main" ]
  
  # Déclencheur manuel que tu peux lancer depuis l'onglet "Actions" de GitHub
  workflow_dispatch:
    inputs:
      vps_action:
        description: 'Action optionnelle à exécuter sur le VPS'
        required: true
        type: choice
        default: 'none'
        options:
        - 'none'
        - 'reset-database'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy project files to VPS
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          source: "."
          target: "/opt/lovely-list"
          rm: true # Supprime les anciens fichiers sur le serveur avant de copier

      - name: Build and Deploy on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/lovely-list
            docker compose build
            docker compose up -d

      # Cette étape ne s'exécute QUE si tu as lancé le workflow manuellement
      # en choisissant "reset-database".
      - name: 🚨 Run Special VPS Action
        if: github.event.inputs.vps_action == 'reset-database'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "⚠️  Réinitialisation de la base de données demandée..."
            cd /opt/lovely-list
            docker compose down
            rm -rf ./data
            mkdir ./data
            docker compose up -d
            echo "✅  Base de données réinitialisée et application redémarrée."