name: Deploy to VPS

on:
  # Déclencheur automatique quand tu push sur la branche main
  push:
    branches: [ "main" ]
  
  # Déclencheur manuel que tu peux lancer depuis l'onglet "Actions" de GitHub
  workflow_dispatch:
    inputs:
      vps_action:
        description: 'Action optionnelle à exécuter sur le VPS'
        required: true
        type: choice
        default: 'none'
        options:
        - 'none'
        - 'reset-database'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lovely-list:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /opt/lovely-list
            docker compose pull
            docker compose up -d

      # -- NOUVELLE ÉTAPE CONDITIONNELLE --
      # Cette étape ne s'exécute QUE si tu as lancé le workflow manuellement
      # en choisissant "reset-database".
      - name: 🚨 Run Special VPS Action
        if: github.event.inputs.vps_action == 'reset-database'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "⚠️  Réinitialisation de la base de données demandée..."
            cd /opt/lovely-list
            docker compose down
            rm -rf ./data
            mkdir ./data
            docker compose up -d
            echo "✅  Base de données réinitialisée et application redémarrée."